<a href="https://colab.research.google.com/github/AlexeyTri/SemMed_fall25/blob/main/HW/HW_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import numpy as np
import random
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

(2 балл)


Создать тензор размерности 5000 X 300 X 70

Рассчитать среднеарифметическое по размерности№2

Рассчитать сумму элементов по размерности№3

Выполнить сложение копии данного тензора и его экземпляром, с примененной фушкцией экспоенты

Выполнить эти же операции на GPU, рассчитать разницу времени между выполнением на CPU и GPU.
Сделать вывод, за счет чего образовалась данная разница

In [6]:
# your code here

X_your_tensor = ...

In [11]:
X = torch.randn(5, 3, 7)

In [ ]:
assert X_your_tensor.shape == (5000, 300, 70)

In [4]:
assert X.shape == (5, 3, 7)

In [15]:
# your code here
X_mean_2 = ...
X_mean_3 = ...

tensor([[ 0.2057,  0.3047, -0.2256],
        [-0.2615,  0.0807, -0.3283],
        [ 0.0980,  0.2211, -0.4315],
        [-0.3076, -0.6968, -0.1656],
        [-0.1662, -0.2649, -0.0536]])

In [17]:
X_mean_2 = X.mean(dim=1)
X_mean_3 = X.mean(dim=2)
X_mean_2.shape, X_mean_3.shape

(torch.Size([5, 7]), torch.Size([5, 3]))

In [9]:
assert X_mean_2.shape == (5000, 70)
assert X_mean_3.shape == (5000, 300)

tensor([[[-8.9030e-01,  1.2356e+00, -8.7757e-01, -2.2814e-01, -7.4793e-02,
           4.2729e-01,  1.0093e+00],
         [ 8.0392e-01, -1.3444e+00,  1.5955e+00,  6.5995e-02,  3.4720e-01,
          -2.9821e+00, -4.5988e-01],
         [-1.3929e+00,  6.8214e-01,  4.5231e-01, -1.7259e+00,  1.2173e-01,
          -9.8514e-01, -2.2370e+00]],

        [[-4.4020e-01,  1.3212e-01,  6.0609e-01,  1.1084e+00,  2.7209e-01,
           4.5994e-01, -9.1792e-01],
         [-1.5528e+00, -5.8904e-02,  4.3983e-01, -9.1302e-03, -4.3733e-01,
           4.6145e-01,  1.5326e+00],
         [-9.9290e-01,  1.7801e-01,  1.5819e+00,  4.0078e-01,  1.2215e+00,
           5.0040e-01,  6.5004e-01]],

        [[ 8.8231e-01,  2.1832e-01,  7.6359e-01, -3.3055e-01, -2.0415e+00,
          -1.2864e+00, -3.9617e-02],
         [-7.0241e-01, -9.5448e-01, -1.7154e+00, -8.6695e-01,  1.9071e-01,
          -5.2654e-01, -1.1184e+00],
         [ 1.7955e+00, -1.2425e+00, -2.4936e-01,  1.8705e-03, -9.0767e-01,
           1.7359e-01, -1

In [19]:
X.sum(dim=2).shape

torch.Size([5, 3])

In [18]:
# your code here
X_sum_3 = ...

tensor([[ 1.4399,  2.1332, -1.5790],
        [-1.8302,  0.5646, -2.2982],
        [ 0.6857,  1.5478, -3.0204],
        [-2.1531, -4.8775, -1.1595],
        [-1.1635, -1.8546, -0.3749]])

In [ ]:
assert X_sum_3.shape == (5000, 300)

In [20]:
# your code here
sum = ...

torch.Size([5, 3, 7])

In [ ]:
assert sum.shape == (5000, 300, 70)

In [ ]:
# GPU

(8 баллов)

AUTOGRAD

Создать тензор Х размерности (150 х 11)

Создать тензор-столбец У размерности (150 х 1), состоящий из соответствующих значений функции f = 7 * X + 13
(для того, чтобы получить корректную размерность в выражении 7*X, необходимо применить функцию sum() с соответствующим параметром dim)

Запустить алгоритм градиетного спуска, для определения параметров w, b (напоминаю, они у нас уже заданы как 7 и 13, соответственно наш алгорит и должен их вычислить), со следующими гиперпараметрами:



1.   loss MSE
2.   learning_rate = 0.1
3.   n_epochs = 100
4.   tolerance = 0.01 (критерий остановки)

**Вывести получившийся тензор w, тензор b, количество эпох**

!Внимание:
*   что нужно сделать с данными перед загрузкой в модель?
*   при расчете параметра tolerance внутри цикла, к разнице значений y и y_pred необходимо применить агрегирующую функцию mean()


In [29]:
# your code here
X =  ...
assert X.shape == (150, 11)

In [98]:
# your code here
w = ...
b = ...

assert w.shape[0] == 11, b.shape[0] == 1

In [101]:
# your code here
y = ...
assert y.shape[0] == 150

In [103]:
learning_rate = # your code here
n_epochs = # your code here
tolerance = # your code here

for epoch in range(n_epochs):
    y_hat = # your code here
    loss = # your code here
    loss # your code here
    with torch.no_grad():
        w # your code here
        b # your code here
        w.# your code here
        b.# your code here
    if tolerance > # your code here:
        print # your code here
        break

Epoch finish: 35, w: tensor([7.0063, 6.9893, 6.9706, 6.9821, 6.9992, 7.0176, 6.9702, 6.9874, 6.9844,
        6.9942, 6.9711], requires_grad=True), b: tensor([12.9934], requires_grad=True)
